version: 0.2

env:
  variables:
    PULUMI_ACCESS_TOKEN: "/usr/lib/jvm/java-8-openjdk-amd64"
  parameter-store:
    LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install:
    commands:
      # pulumi
      - curl -L https://get.pulumi.com/ | bash -s -- --version 0.16.2
      - export PATH=$PATH:$HOME/.pulumi/bin
  build:
    commands:
      - update_pulumi_stack.sh
