version: 0.2

phases:
  install:
    commands:
      # pulumi
      - curl -L https://get.pulumi.com/ | bash -s -- --version 0.16.2
      - export PATH=$PATH:$HOME/.pulumi/bin
  build:
    commands:
      - update_pulumi_stack.sh
